In [1]:
from pathlib import Path
import bids
import numpy as np

In [9]:
pwd

'/home/jdaoust/JDaoust_project/scripts'

In [10]:
layout = bids.BIDSLayout("../../../../mnt/c/Users/justi/Documents/Universite_Laval/Doctorat/Cours/Brainhack/BIDS")
layout

BIDS Layout: ...torat/Cours/Brainhack/raw_BIDS | Subjects: 1 | Sessions: 4 | Runs: 3

In [22]:
bold_images = layout.get(suffix="bold", extension=[".nii", ".nii.gz"])

In [31]:
for bold in bold_images:
    TR = bold.get_metadata()["RepetitionTime"]
    img = bold.get_image()
    zooms = img.header.get_zooms()
    if not np.isclose(zooms[3], TR):
        old_path = Path(bold)
        new_path = old_path.with_name(f"{old_path.stem}_fixed.nii.gz")
        img.header.set_zooms(zooms[:3] + (TR,))
        img.to_filename(new_path)


<class 'nibabel.nifti1.Nifti1Image'>
data shape (80, 80, 45, 166)
affine:
[[   3.            0.            0.         -118.5       ]
 [   0.            2.43105865   -1.75781953  -76.59324646]
 [   0.            1.75782633    2.43104935  -92.85631561]
 [   0.            0.            0.            1.        ]]
metadata:
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  4  80  80  45 166   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [1.        3.        3.        2.9999883 2.75      0.        0.
 0.       ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min        


<class 'nibabel.nifti1.Nifti1Image'>
data shape (80, 80, 45, 159)
affine:
[[ 2.99861002e+00  9.13122669e-02  1.19571168e-05 -1.22051323e+02]
 [-7.90729970e-02  2.59688020e+00 -1.49997962e+00 -8.68953629e+01]
 [-4.56660874e-02  1.49929166e+00  2.59807086e+00 -1.01348831e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
metadata:
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 16384
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  4  80  80  45 159   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [1.        3.        3.        2.9999852 2.75      0.        0.
 0.       ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
c


<class 'nibabel.nifti1.Nifti1Image'>
data shape (80, 80, 45, 159)
affine:
[[ 2.99281216e+00  1.18250139e-01  1.70564175e-01 -1.23617058e+02]
 [-2.42078453e-02  2.64750957e+00 -1.41070008e+00 -8.93542328e+01]
 [-2.06130266e-01  1.40595531e+00  2.64209867e+00 -8.22874756e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
metadata:
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 16384
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  4  80  80  45 159   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [1.        3.        3.        2.9999754 2.75      0.        0.
 0.       ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
c


<class 'nibabel.nifti1.Nifti1Image'>
data shape (80, 80, 45, 179)
affine:
[[   3.            0.            0.         -125.11322784]
 [   0.            2.54471445   -1.58883035  -73.63047028]
 [   0.            1.58884513    2.54469061 -191.12062073]
 [   0.            0.            0.            1.        ]]
metadata:
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 16384
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  4  80  80  45 179   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [1.       3.       3.       2.999972 2.75     0.       0.       0.      ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min      


<class 'nibabel.nifti1.Nifti1Image'>
data shape (80, 80, 45, 170)
affine:
[[ 2.99686646e+00 -1.34169400e-01 -2.81152502e-02 -1.11261658e+02]
 [ 9.99585688e-02  2.55985546e+00 -1.56113446e+00 -8.57816162e+01]
 [ 9.38092992e-02  1.55856943e+00  2.56164813e+00 -9.14384918e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
metadata:
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 16384
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  4  80  80  45 170   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [1.        3.        3.        2.9999955 2.75      0.        0.
 0.       ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
c

In [34]:
import pandas as pd
import scipy

In [ ]:
files <- list.files(path = '/path/to/your/folder', 
            pattern = '\\.txt$', full.names = TRUE)
map_dfr(files, read_table) %>%
      write_tsv(path = '/path/to/your/folder/yourfile.tsv')

In [47]:
mat = scipy.io.loadmat('../../../../mnt/c/Users/justi/Documents/Universite_Laval/Maitrise/Gut-Brain/Tache_fMRI/EVs/bariatric_RND050_session4_run2_events.mat')

In [53]:
df = pd.DataFrame(mat(['onsets','durations'])[0])
df

TypeError: 'dict' object is not callable

In [48]:
mat

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Mon Aug 22 20:33:58 2022',
 '__version__': '1.0',
 '__globals__': [],
 'durations': array([[array([[2.08 ],
                [2.003],
                [2.253],
                [1.343],
                [1.851],
                [1.949],
                [1.867],
                [1.581],
                [1.379],
                [1.627],
                [1.113],
                [1.971],
                [0.632],
                [1.993],
                [2.86 ],
                [2.271],
                [1.573],
                [2.199],
                [1.836],
                [2.158],
                [2.159],
                [2.572],
                [1.565],
                [1.958],
                [2.52 ],
                [2.558],
                [1.485],
                [1.591],
                [1.646],
                [1.765],
                [2.342],
                [1.628],
                [1.619],
                [1.722]

In [ ]:
df.to_csv('mydata.csv',index=False)